### ISSUE TITLE
Security Groups - Unrestricted Access

### ISSUE THREAD

**Issue by mTouhid** [ministryofjustice/staff-device-logging-infrastructure#47]
Several security groups have unrestricted access.

- [ ] staff-device-production-infra-functionbeats
- [ ] staff-device-production-infra-syslog-syslog-container
- [ ] staff-device-production-infra-syslog-syslog-container

- [ ] Update Trusted Advisor  

According to AWS security advisory report, these security groups need better IP restrictions.

**Comment by mitchdawson1982** [comment]
Establish if 0.0.0.0/0 rules are valid, or if we can restrict them.

**Comment by Gary-H9** [comment]
`staff-device-production-infra-functionbeats` is permitted. 
`staff-device-production-infra-syslog-syslog-container` is also permitted. 
Trusted Advisor updated in prod.
